version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: News
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    ports:
      - "8080:80"
    networks:
      - laravel_network
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    container_name: news_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: news
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

  redis:
    image: redis:latest
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  db_data:
